version: "3.7"
x-sign: &sign-env
  environment:
    - NUM_WORKERS
    - TOPOLOGY_NAME=signTest
    - BENCH=BenchmarkSignNoNetwork
    - NUM_MULTISIG
    - GOGC=11000
    - BATCH_VERIFICATION
    - MAP_TYPE

services:
  base:
    build: .
    image: base

  server:
    build: ./server
    depends_on:
      - base
    ports:
      - "6666:6666"
    environment:
      - TOPOLOGY=dockerSimple

  server_shard_0:
    build: ./server
    depends_on:
      - base
    ports:
      - "6666:6666"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=0

  server_shard_1:
    build: ./server
    depends_on:
      - base
    ports:
      - "6667:6667"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=1

  server_shard_2:
    build: ./server
    depends_on:
      - base
    ports:
      - "6668:6668"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=2

  server_shard_3:
    build: ./server
    depends_on:
      - base
    ports:
      - "6669:6669"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=3

  server_shard_4:
    build: ./server
    depends_on:
      - base
    ports:
      - "6670:6670"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=4

  agents:
    build: ./test/agents
    depends_on:
      - base
    environment:
      - TOPOLOGY=aws
      - NUM_WORKERS=64

  sign_benchmark_1:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    deploy:
      resources:
        limits:
          cpus: '1'

  sign_benchmark_2:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    deploy:
      resources:
        limits:
          cpus: '2'

  sign_benchmark_4:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    deploy:
      resources:
        limits:
          cpus: '4'

  sign_benchmark_8:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    deploy:
      resources:
        limits:
          cpus: '8'

  sign_benchmark_16:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    deploy:
      resources:
        limits:
          cpus: '16'

  sign_benchmark_32:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    deploy:
      resources:
        limits:
          cpus: '32'

  sign_benchmark_64:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    deploy:
      resources:
        limits:
          cpus: '64'

  verify_batch_benchmark_1:
    build: ./test/crypto/ed25519
    depends_on:
      - base
    environment:
      - BENCH=BenchmarkVerifyBatch64
      - NUM_WORKERS=1
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '1'

  sign_test_1:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '1'

  sign_test_2:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '2'

  sign_test_4:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '4'

  sign_test_8:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '8'

  sign_test_16:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '16'

  sign_test_32:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '32'

  sign_test_64:
    build: ./test/sign
    depends_on:
      - base
    <<: *sign-env
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '64'

  map_benchmark_1:
    build: ./test/map
    depends_on:
      - base
    environment:
      - BENCH
      - TEST
      - NUM_WORKERS=1
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '1'

  map_benchmark_2:
    build: ./test/map
    depends_on:
      - base
    environment:
      - BENCH
      - TEST
      - NUM_WORKERS=2
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '2'

  map_benchmark_4:
    build: ./test/map
    depends_on:
      - base
    environment:
      - BENCH
      - TEST
      - NUM_WORKERS=4
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '4'


  map_benchmark_8:
    build: ./test/map
    depends_on:
      - base
    environment:
      - BENCH
      - TEST
      - NUM_WORKERS=8
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '8'


  map_benchmark_16:
    build: ./test/map
    depends_on:
      - base
    environment:
      - BENCH
      - TEST
      - NUM_WORKERS=16
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '16'


  map_benchmark_32:
    build: ./test/map
    depends_on:
      - base
    environment:
      - BENCH
      - TEST
      - NUM_WORKERS=32
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '32'


  map_benchmark_64:
    build: ./test/map
    depends_on:
      - base
    environment:
      - BENCH
      - TEST
      - NUM_WORKERS=64
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '64'

