version: "3.7"
x-sign-bench: &sign-bench-env
  build: ./test/sign
  depends_on:
    - base
  environment:
    - NUM_WORKERS
    - TOPOLOGY_NAME=signTest
    - BENCH=BenchmarkSignNoNetwork
    - NUM_MULTISIG
    - GOGC=11000
    - BATCH_VERIFICATION
    - MAP_TYPE

x-sign-test: &sign-test-env
  build: ./test/sign
  depends_on:
    - base
  environment:
    - NUM_WORKERS
    - TOPOLOGY_NAME=signTest
    - TEST=TestSignNoNetwork
    - NUM_MULTISIG
    - GOGC=11000
    - BATCH_VERIFICATION
    - MAP_TYPE
  ports:
    - "6666:6666"

x-map-bench: &map-bench-env
  build: ./test/map
  depends_on:
    - base
  environment:
    - BENCH=BenchmarkFunSet
    - NUM_WORKERS
    - GOGC=11000

x-map-test: &map-test-env
  build: ./test/map
  depends_on:
    - base
  environment:
    - TEST=TestFunSetInserts
    - NUM_WORKERS
    - GOGC=11000


services:
  base:
    build: .
    image: base

  # Important: all servers launch on the same port (unlike local configurations)
  server:
    build: ./server
    depends_on:
      - base
    ports:
      - "6666:6666"
    environment:
      - TOPOLOGY
      - ADDRESS
      - POOLING

  server_shard_0:
    build: ./server
    depends_on:
      - base
    ports:
      - "6666:6666"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=0

  server_shard_1:
    build: ./server
    depends_on:
      - base
    ports:
      - "6667:6667"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=1

  server_shard_2:
    build: ./server
    depends_on:
      - base
    ports:
      - "6668:6668"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=2

  server_shard_3:
    build: ./server
    depends_on:
      - base
    ports:
      - "6669:6669"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=3

  server_shard_4:
    build: ./server
    depends_on:
      - base
    ports:
      - "6670:6670"
    environment:
      - TOPOLOGY=aws
      - INSTANCE=4

  agents:
    build: ./test/agents
    depends_on:
      - base
    environment:
      - TOPOLOGY
      - NUM_WORKERS=64

  sign_benchmark_1:
    <<: *sign-bench-env
    deploy:
      resources:
        limits:
          cpus: '1'

  sign_benchmark_2:
    <<: *sign-bench-env
    deploy:
      resources:
        limits:
          cpus: '2'

  sign_benchmark_4:
    <<: *sign-bench-env
    deploy:
      resources:
        limits:
          cpus: '4'

  sign_benchmark_8:
    <<: *sign-bench-env
    deploy:
      resources:
        limits:
          cpus: '8'

  sign_benchmark_16:
    <<: *sign-bench-env
    deploy:
      resources:
        limits:
          cpus: '16'

  sign_benchmark_32:
    <<: *sign-bench-env
    deploy:
      resources:
        limits:
          cpus: '32'

  sign_benchmark_64:
    <<: *sign-bench-env
    deploy:
      resources:
        limits:
          cpus: '64'

  benchmark_bls:
    build: ./test/crypto/bls
    depends_on:
      - base
    environment:
      - BENCH
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '1'

  benchmark_ed25519:
    build: ./test/crypto/ed25519
    depends_on:
      - base
    environment:
      - BENCH
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '1'

  benchmark_merkle:
    build: ./test/crypto/merkle
    depends_on:
      - base
    environment:
      - BENCH
      - POOL_SIZE
      - BENCHTIME
      - GOGC=11000
    deploy:
      resources:
        limits:
          cpus: '1'

  sign_test_1:
    <<: *sign-test-env
    deploy:
      resources:
        limits:
          cpus: '1'

  sign_test_2:
    <<: *sign-test-env
    deploy:
      resources:
        limits:
          cpus: '2'

  sign_test_4:
    <<: *sign-test-env
    deploy:
      resources:
        limits:
          cpus: '4'

  sign_test_8:
    <<: *sign-test-env
    deploy:
      resources:
        limits:
          cpus: '8'

  sign_test_16:
    <<: *sign-test-env
    deploy:
      resources:
        limits:
          cpus: '16'

  sign_test_32:
    <<: *sign-test-env
    deploy:
      resources:
        limits:
          cpus: '32'

  sign_test_64:
    <<: *sign-test-env
    deploy:
      resources:
        limits:
          cpus: '64'

  map_benchmark_1:
    <<: *map-bench-env
    deploy:
      resources:
        limits:
          cpus: '1'

  map_benchmark_2:
    <<: *map-bench-env
    deploy:
      resources:
        limits:
          cpus: '2'

  map_benchmark_4:
    <<: *map-bench-env
    deploy:
      resources:
        limits:
          cpus: '4'


  map_benchmark_8:
    <<: *map-bench-env
    deploy:
      resources:
        limits:
          cpus: '8'


  map_benchmark_16:
    <<: *map-bench-env
    deploy:
      resources:
        limits:
          cpus: '16'


  map_benchmark_32:
    <<: *map-bench-env
    deploy:
      resources:
        limits:
          cpus: '32'


  map_benchmark_64:
    <<: *map-bench-env
    deploy:
      resources:
        limits:
          cpus: '64'

  map_test_64:
    <<: *map-test-env
    deploy:
      resources:
        limits:
          cpus: '64'
