version: "3.7"
services:
  base:
    build: .
    image: base

  server:
    build: ./server
    depends_on:
      - base
    ports:
      - "6666:6666"
    environment:
      - TOPOLOGY=aws

  agents:
    build: ./benchmark/agents
    depends_on:
      - server
    environment:
      - TOPOLOGY=aws

  single_thread:
    build: ./benchmark/sign
    depends_on:
      - base
    environment:
      - TOPOLOGY=aws