version: "3.7"
services:
  base:
    build: .
    image: base

  server:
    build: ./server
    depends_on:
      - base
    ports:
      - "6666:6666"
    environment:
      - TOPOLOGY

  agents:
    build: ./benchmark/agents
    depends_on:
      - base
    environment:
      - TOPOLOGY
      - NUM_WORKERS

  sign_benchmark:
    build: ./benchmark/sign
    depends_on:
      - base
    environment:
      - TOPOLOGY=aws
      - BENCH=BenchmarkSignNoNetwork
      - NUM_WORKERS=1
    deploy:
      resources:
        limits:
          cpus: '1'

  # runs for 1 million tx and does not output a benchmark, but exposes pprog
  sign_test:
    build: ./benchmark/sign
    depends_on:
      - base
    environment:
      - TOPOLOGY=aws
      - TEST=TestSignNoNetwork
      - NUM_WORKERS=1
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '1'