version: "3.7"
services:
  base:
    build: .
    image: base

  server:
    build: ./server
    depends_on:
      - base
    ports:
      - "6666:6666"
    environment:
      - TOPOLOGY

  agents:
    build: ./benchmark/agents
    depends_on:
      - base
    environment:
      - TOPOLOGY
      - NUM_WORKERS

  single_thread:
    build: ./benchmark/sign
    depends_on:
      - base
    environment:
      - TOPOLOGY=aws
      - TEST=BenchmarkSignNoNetwork
      - NUM_WORKERS
    ports:
      - "6666:6666"
    deploy:
      resources:
        limits:
          cpus: '8'