name: Push to ETH GitLab
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        pub: ${{ secrets.ETH_PUB }}
        key: ${{ secrets.ETH_KEY }}
    steps:
    - name: test git
      run: |
        mkdir -p .ssh
        ssh-keygen -b 2048 -t rsa -f .ssh/id_rsa -q -N ""
        which git
      
