name: Push to ETH GitLab
on: [push]

jobs:
  build:
    name: Push
    runs-on: ubuntu-latest
    env:
        pub: ${{ secrets.ETH_PUB }}
        key: ${{ secrets.ETH_KEY }}
    steps:
    - name: test git
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""
        echo "${{ secrets.ETH_PUB }}" > ~/.ssh/id_rsa.pub
        echo "${{ secrets.ETH_KEY }}" > ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa
        git init
        git remote add origin git@gitlab.ethz.ch:disco-students/fs20/mmathys-consensus-free-transaction-systems.git
        ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; git pull origin master'
#        git pull origin master
#        git push origin master
