name: Push to ETH GitLab
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        pub: ${{ secrets.ETH_PUB }}
        key: ${{ secrets.ETH_KEY }}
    steps:
    - name: test git
      run: |
        cd .ssh 
        which git
      
